### ISSUE TITLE
No Phar Files?

### ISSUE THREAD

**Issue by DaPigGuy** [mamayadesu/PocketMinePlugins#1]
Can you upload the phar files of your plugins? Thanks!

**Comment by sbayandin** [comment]
I will upload phar files on my website. Wait.

**Comment by DaPigGuy** [comment]
Ok

**Comment by sbayandin** [comment]
https://github.com/mamayadesu/PocketMinePlugins/blob/master/README.md

**Comment by DaPigGuy** [comment]
Cool
